#!/bin/sh

## semplicelive - Live-specific user settings for Semplice Live
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2011-2014 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

Cmdline()
{
	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init() {
	
	# Checking if package is installed or already configured
	#if [ ! -e /var/lib/dpkg/info/foobar.list ] || \
	#   [ -e /var/lib/live/config/foobar ]
	#then
	#	return
	#fi

	echo -n " semplicelive"

}

Config()
{
	# Set semplice-live-mode to yeahh, this is a live system that has been unconfigured.
	echo "yeahh" > /etc/semplice-live-mode

	if [ "$LIVE_USERNAME" ]; then
		# Append to user's .bashrc some strings to make TTY more familiar if X doesn't work
		cat >> /home/$LIVE_USERNAME/.bashrc <<EOF
if [ "\$TERM" = "linux" ]; then
cat <<EOW

#################################################################
# Hello! Welcome to the Semplice Live System!                   #
# If you see this message there are four reasons:               #
#  1) Semplice is booting and you'll get to the graphical       #
#     system soon                                               #
#  2) You have selected your language and keyboard              #
#     and Semplice is applying your settings                    #
#  3) Semplice hasn't detected your graphics configuration      #
#     and then you can't use system without manual              #
#     intervent. If this is the case, type "sudo reboot"        #
#     (without quotes) and press ENTER to reboot the system.    #
#  4) You're a linux geek and you want to do some               #
#     cool stuff in the shell. Yay!                             #
#################################################################
EOW
fi
EOF
	fi

	# Creating state file
	touch /var/lib/live/config/semplicelive
}

Cmdline
Init
Config
