#!/bin/bash

## nonfree - If false, remove all nonfree bits installed from system-nonfree
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2011-2014 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Cmdline()
{
	
	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.nonfree=false|nonfree=false)
				LIVE_ENABLE="yay"
				;;
		esac
	done
	
}

Init() {
	
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/meta-nonfree.list ] || \
	   [ -e /var/lib/live/config/meta-nonfree ]
	then
		exit 0
	fi

	echo -n " nonfree"

}

Config()
{
	
	if [ "$LIVE_ENABLE" ]; then
		# Begin.
		
		/usr/bin/remove_meta.sh meta-nonfree -n -v &> /removed_nonfree.status
	fi

	# Creating state file
	touch /var/lib/live/config/nonfree
}

Cmdline
Init
Config
