#!/bin/bash

## nonfree - If false, remove all nonfree bits installed from system-nonfree
## Copyright (C) 2011 Eugenio "g7" Paolantonio <morarossa@gmail.com>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


nonfree ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/system-nonfree.list ] || \
	   [ -e /var/lib/live/config/system-nonfree ]
	then
		return
	fi

	echo -n " nonfree"

	# Get username
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.nonfree=false|nonfree=false)
				LIVE_ENABLE="yay"
				;;
		esac
	done
	

	Configure_nonfree
}

Configure_nonfree ()
{
	
	if [ "$LIVE_ENABLE" ]; then
		# Begin.
		
		/usr/bin/remove_meta.sh system-nonfree -n -v &> /removed_nonfree.status
	fi

	# Creating state file
	touch /var/lib/live/config/nonfree
}

nonfree
