#!/bin/sh

## xscreensaver - Disable screensaver autolock in live mode
## Copyright (C) 2013 Eugenio "g7" Paolantonio <morarossa@gmail.com>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


xscreensaver ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/xscreensaver.list ] || \
	   [ -e /var/lib/live/config/xscreensaver ]
	then
		return
	fi

	echo -n " xscreensaver"

	# Get username
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	if [ "$LIVE_USERNAME" ]; then
		Configure_xscreensaver
	fi
}

Configure_xscreensaver ()
{
	echo "lock: False" >> /home/$LIVE_USERNAME/.xscreensaver

	# Creating state file
	touch /var/lib/live/config/xscreensaver
}

xscreensaver
