#!/bin/sh

## zramcfg - Configure zram in Semplice Live
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2013-2014 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Cmdline()
{

	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.nozramcfg|nozramcfg)
				CONFIG="disabled"
				;;
		esac
	done

}

Init() {

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/zramcfg.list ] || \
	   [ -e /var/lib/live/config/zramcfg ]
	then
		exit 0
	fi

	echo -n " zramcfg"

}

Config()
{
	if [ "$CONFIG" != "disabled" ]; then
		/usr/bin/zramcfg -q
		
		NUM_DEVICES="`grep -c processor /proc/cpuinfo`"
		
		modprobe zram num_devices=$NUM_DEVICES
	fi

	# Creating state file
	touch /var/lib/live/config/zramcfg
}

Cmdline
Init
Config
