#!/bin/sh

## xscreensaver-forced - Forcibly configure xscreensaver in Semplice Live
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2013-2015 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Cmdline()
{

	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

}

Init() {

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/xscreensaver.list ] || \
	   [ -e /var/lib/live/config/xscreensaver-forced ]
	then
		exit 0
	fi

	echo -n " xscreensaver-forced"

}

Config()
{
	if [ -n "$LIVE_USERNAME" ]; then
		echo "lock: False" >> /home/$LIVE_USERNAME/.xscreensaver
	fi

	# Creating state file
	touch /var/lib/live/config/xscreensaver-forced
}

Cmdline
Init
Config
